/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package notebook.controller;

public class controller {
    public boolean someLibraryMethod() {
        return true;
    }
}
