/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package notebook.controller;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        controller classUnderTest = new controller();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
