apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  labels:
    app: test-notebook
  name: test-notebook
  namespace: test-namespace
spec:
  volumeClaim:
  - name: workspace-test-notebook
    size: 10Mi
  template:
    spec:
      containers:
      - env: []
        image: gcr.io/kubeflow-images-public/tensorflow-1.15.2-notebook-cpu:1.0.0
        name: test-notebook
        resources:
          requests:
            cpu: "0.5"
            memory: 1.0Gi
        volumeMounts:
        - mountPath: /home/jovyan
          name: workspace-test-notebook
        - mountPath: /dev/shm
          name: dshm
      serviceAccountName: default
      ttlSecondsAfterFinished: 300
      volumes:
      - name: workspace-test-notebook
        persistentVolumeClaim:
          claimName: workspace-test-notebook
      - emptyDir:
          medium: Memory
        name: dshm
